version: 2.1
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:bionic-curl
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build container
          command: docker-compose build
      - run:
          name: Run container
          command: docker-compose up -d
  
  router-tests:
    docker:
      - image: cimg/node:21.7.1
    working_directory: ~/.circleci/config.yml
    steps:
      - checkout
      - run:
          name: Current Directory
          command: |
            cd src
            npm install
