version: "3.8"

services:
  mysqldb:
    image: mysql
    container_name: mysqldb
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql

  app:
    container_name: webserver
    depends_on:
      - mysqldb
    build:
      context: ./webserver
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./.env
    volumes:
      - "./webserver:/app"
      - "/app/node_modules"
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=mysqldb
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - DB_NAME=$MYSQLDB_DATABASE
      - DB_PORT=$MYSQLDB_DOCKER_PORT
      - FIRST_RUN=true
    stdin_open: true
    tty: true

networks:
  my-network:
    driver: bridge
volumes:
  db:
